FROM thunderk/base-debian
RUN install-packages g++ python-dev python-numpy libgtk-3-dev python-gi-dev gir1.2-gtk-3.0 python-gi-cairo swig scons gettext libpng12-dev liblcms2-dev libjson-c-dev
WORKDIR /code
RUN mkdir -p /root/.config
RUN mkdir -p /root/.local/share

